FROM ubuntu:focal

RUN apt-get update && apt-get install -y \
    net-tools \
    iputils-ping \
    iproute2 \
    tshark \
    tcpdump \
    ftp \ 
    iperf \
    wget \
    curl

#RUN add-apt-repository ppa:keithw/mahimahi
#RUN apt-get update
#RUN apt-get install mahimahi -y

#WORKDIR /app
#COPY . /app
